import {Exo_2, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin"],
  weight: ["300", "400"],
})

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "700"]
})

export const metadata = {
  title: "Neubodhi Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${exo2.variable} ${orbitron.variable} antialiased bg-[#F8F8FF] overflow-x-hidden`}
      >
        <Navbar />
        
        {children}

        <Footer />
      </body>
    </html>
  );
}
